name: Metrics Feeds

on:
  schedule:
    # Runs every 15 minutes
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: German News
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.dailydevops.de.rss.svg
          token: NOT_NEEDED
          base: ""
          committer_message: Update ${filename} [skip ci]
          plugin_rss: yes
          plugin_rss_source: https://daily-devops.net/de/authors/martin/feed.rss
          plugin_rss_limit: 10
          
      - name: English News
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.dailydevops.en.rss.svg
          token: NOT_NEEDED
          base: ""
          committer_message: Update ${filename} [skip ci]
          plugin_rss: yes
          plugin_rss_source: https://daily-devops.net/en/authors/martin/feed.rss
          plugin_rss_limit: 10
